/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 19-oct.-2022 5:08:19 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

 

 

 

/* Drop Tables */

DROP TABLE IF EXISTS Ingrediente CASCADE
;

DROP TABLE IF EXISTS Menu CASCADE
;

DROP TABLE IF EXISTS Menu_Pedido CASCADE
;

DROP TABLE IF EXISTS Menu_Producto CASCADE
;

DROP TABLE IF EXISTS Menu_Restaurante CASCADE
;

DROP TABLE IF EXISTS Pedido CASCADE
;

DROP TABLE IF EXISTS Producto CASCADE
;

DROP TABLE IF EXISTS Producto_Ingrediente CASCADE
;

DROP TABLE IF EXISTS Restaurante CASCADE
;

DROP TABLE IF EXISTS Tipo_Producto CASCADE
;

DROP TABLE IF EXISTS Tipo_Usuario CASCADE
;

DROP TABLE IF EXISTS Unidad_Medida CASCADE
;

DROP TABLE IF EXISTS Usuario CASCADE
;

/* Create Tables */

CREATE TABLE Ingrediente
(
	ID_Ingrediente varchar(15) NOT NULL,
	Nombre_Ingrediente varchar(35) NOT NULL,
	Unidades integer NOT NULL,
	ID_Unidad_Medida integer NULL
)
;

CREATE TABLE Menu
(
	ID_Menu varchar(15) NOT NULL,
	Nombre_Menu varchar(40) NOT NULL,
	Precio_Menu bigint NOT NULL,
	Personalizable boolean NOT NULL,
	Imagen varchar(100) NULL
)
;

CREATE TABLE Menu_Pedido
(
	ID_Menu_Pedido serial NOT NULL,
	ID_Pedido varchar(15) NULL,
	ID_Menu varchar(15) NULL
)
;

CREATE TABLE Menu_Producto
(
	ID_Menu_Producto serial NOT NULL,
	ID_Menu varchar(15) NULL,
	ID_Producto varchar(15) NULL
)
;

CREATE TABLE Menu_Restaurante
(
	ID_Menu_Restaurante serial NOT NULL,
	ID_Menu varchar(15) NULL,
	NIT_Restaurante varchar(15) NULL
)
;

CREATE TABLE Pedido
(
	ID_Pedido varchar(15) NOT NULL,
	Monto bigint NOT NULL,
	Direccion varchar(50) NOT NULL,
	Fecha date NOT NULL,
	ID_Usuario varchar(15) NULL
)
;

CREATE TABLE Producto
(
	ID_Producto varchar(15) NOT NULL,
	Nombre_Prd varchar(30) NOT NULL,
	Precio_Prd bigint NOT NULL,
	Personalizable boolean NOT NULL,
	Imagen varchar(100) NULL,
	ID_Tipo_Prd integer NULL
)
;

CREATE TABLE Producto_Ingrediente
(
	ID_Producto_Ingrediente serial NOT NULL,
	ID_Producto varchar(15) NULL,
	ID_Ingrediente varchar(15) NULL
)
;

CREATE TABLE Restaurante
(
	NIT_Restaurante varchar(15) NOT NULL,
	Nombre_Restaurante varchar(50) NOT NULL,
	Telefono varchar(20) NOT NULL,
	Especialidad varchar(30) NOT NULL
)
;

CREATE TABLE Tipo_Producto
(
	ID_Tipo_Prd integer NOT NULL,
	Nombre_Tipo_Prd varchar(20) NOT NULL
)
;

CREATE TABLE Tipo_Usuario
(
	ID_Tipo_Usuario integer NOT NULL,
	Nombre_Tipo_Usuario varchar(15) NULL
)
;

CREATE TABLE Unidad_Medida
(
	ID_Unidad_Medida integer NOT NULL,
	Unidad_Medida varchar(15) NOT NULL
)
;

CREATE TABLE Usuario
(
	ID_Usuario varchar(15) NOT NULL,
	Nombre_Usuario varchar(40) NOT NULL,
	Correo varchar(40) NOT NULL,
	"Contraseña" varchar(30) NOT NULL,
	Celular varchar(20) NOT NULL,
	ID_Tipo_Usuario integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Ingrediente ADD CONSTRAINT PK_Ingrediente
	PRIMARY KEY (ID_Ingrediente)
;

CREATE INDEX IXFK_Ingrediente_Unidad_Medida ON Ingrediente (ID_Unidad_Medida ASC)
;

ALTER TABLE Menu ADD CONSTRAINT PK_Menu
	PRIMARY KEY (ID_Menu)
;

ALTER TABLE Menu_Pedido ADD CONSTRAINT PK_Menu_Pedido
	PRIMARY KEY (ID_Menu_Pedido)
;

CREATE INDEX IXFK_Menu_Pedido_Menu ON Menu_Pedido (ID_Menu ASC)
;

CREATE INDEX IXFK_Menu_Pedido_Pedido ON Menu_Pedido (ID_Pedido ASC)
;

ALTER TABLE Menu_Producto ADD CONSTRAINT PK_Menu_Producto
	PRIMARY KEY (ID_Menu_Producto)
;

CREATE INDEX IXFK_Menu_Producto_Menu ON Menu_Producto (ID_Menu ASC)
;

CREATE INDEX IXFK_Menu_Producto_Producto ON Menu_Producto (ID_Producto ASC)
;

ALTER TABLE Menu_Restaurante ADD CONSTRAINT PK_Menu_Restaurante
	PRIMARY KEY (ID_Menu_Restaurante)
;

CREATE INDEX IXFK_Menu_Restaurante_Menu ON Menu_Restaurante (ID_Menu ASC)
;

CREATE INDEX IXFK_Menu_Restaurante_Restaurante ON Menu_Restaurante (NIT_Restaurante ASC)
;

ALTER TABLE Pedido ADD CONSTRAINT PK_Pedido
	PRIMARY KEY (ID_Pedido)
;

CREATE INDEX IXFK_Pedido_Usuario ON Pedido (ID_Usuario ASC)
;

ALTER TABLE Producto ADD CONSTRAINT PK_Producto
	PRIMARY KEY (ID_Producto)
;

CREATE INDEX IXFK_Producto_Tipo_Producto ON Producto (ID_Tipo_Prd ASC)
;

ALTER TABLE Producto_Ingrediente ADD CONSTRAINT PK_Producto_Ingrediente
	PRIMARY KEY (ID_Producto_Ingrediente)
;

CREATE INDEX IXFK_Producto_Ingrediente_Ingrediente ON Producto_Ingrediente (ID_Ingrediente ASC)
;

CREATE INDEX IXFK_Producto_Ingrediente_Producto ON Producto_Ingrediente (ID_Producto ASC)
;

ALTER TABLE Restaurante ADD CONSTRAINT PK_Restaurante
	PRIMARY KEY (NIT_Restaurante)
;

ALTER TABLE Tipo_Producto ADD CONSTRAINT PK_Tipo_Producto
	PRIMARY KEY (ID_Tipo_Prd)
;

ALTER TABLE Tipo_Usuario ADD CONSTRAINT PK_Tipo_Usuario
	PRIMARY KEY (ID_Tipo_Usuario)
;

ALTER TABLE Unidad_Medida ADD CONSTRAINT PK_Unidad_Medida
	PRIMARY KEY (ID_Unidad_Medida)
;

ALTER TABLE Usuario ADD CONSTRAINT PK_Usuario
	PRIMARY KEY (ID_Usuario)
;

CREATE INDEX IXFK_Usuario_Tipo_Usuario ON Usuario (ID_Tipo_Usuario ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE Ingrediente ADD CONSTRAINT FK_Ingrediente_Unidad_Medida
	FOREIGN KEY (ID_Unidad_Medida) REFERENCES Unidad_Medida (ID_Unidad_Medida) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Menu_Pedido ADD CONSTRAINT FK_Menu_Pedido_Menu
	FOREIGN KEY (ID_Menu) REFERENCES Menu (ID_Menu) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Menu_Pedido ADD CONSTRAINT FK_Menu_Pedido_Pedido
	FOREIGN KEY (ID_Pedido) REFERENCES Pedido (ID_Pedido) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Menu_Producto ADD CONSTRAINT FK_Menu_Producto_Menu
	FOREIGN KEY (ID_Menu) REFERENCES Menu (ID_Menu) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Menu_Producto ADD CONSTRAINT FK_Menu_Producto_Producto
	FOREIGN KEY (ID_Producto) REFERENCES Producto (ID_Producto) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Menu_Restaurante ADD CONSTRAINT FK_Menu_Restaurante_Menu
	FOREIGN KEY (ID_Menu) REFERENCES Menu (ID_Menu) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Menu_Restaurante ADD CONSTRAINT FK_Menu_Restaurante_Restaurante
	FOREIGN KEY (NIT_Restaurante) REFERENCES Restaurante (NIT_Restaurante) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Pedido ADD CONSTRAINT FK_Pedido_Usuario
	FOREIGN KEY (ID_Usuario) REFERENCES Usuario (ID_Usuario) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Producto ADD CONSTRAINT FK_Producto_Tipo_Producto
	FOREIGN KEY (ID_Tipo_Prd) REFERENCES Tipo_Producto (ID_Tipo_Prd) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Producto_Ingrediente ADD CONSTRAINT FK_Producto_Ingrediente_Ingrediente
	FOREIGN KEY (ID_Ingrediente) REFERENCES Ingrediente (ID_Ingrediente) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Producto_Ingrediente ADD CONSTRAINT FK_Producto_Ingrediente_Producto
	FOREIGN KEY (ID_Producto) REFERENCES Producto (ID_Producto) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Usuario ADD CONSTRAINT FK_Usuario_Tipo_Usuario
	FOREIGN KEY (ID_Tipo_Usuario) REFERENCES Tipo_Usuario (ID_Tipo_Usuario) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

 

 

 

 
